FROM node:20-alpine AS build

WORKDIR /app

COPY client/package*.json ./client/
WORKDIR /app/client
RUN npm install

WORKDIR /app
COPY client ./client
COPY shared ./shared
WORKDIR /app/client
RUN npm run build

FROM nginx:alpine

COPY --from=build /app/client/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
