services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  server:
    build:
      context: ./
      dockerfile: server/Dockerfile
    environment:
      REDIS_URL: redis://redis:6379
    ports:
      - "8000:8000"
    depends_on:
      - redis

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - server
